services:
  php:
    container_name: listas-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
      - mailhog

  db:
    container_name: listas-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: listas
      MYSQL_USER: listas
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - listas_db:/var/lib/mysql

  nginx:
    container_name: listas-nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  mailhog:
    container_name: listas-mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"  
      - "1025:1025"  

volumes:
  listas_db: