<?php
namespace App\DataFixtures;

use App\Entity\Item;
use App\ValueObject\Slug;
use Doctrine\Persistence\ObjectManager;
use Doctrine\Bundle\FixturesBundle\Fixture;

class ItemOtrosFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
       
        $items = [
            ['name' => 'Flan', 'errors' => ['Flan', 'Fflan', 'Flann']],
            ['name' => 'Natillas', 'errors' => ['Natillas', 'Natias', 'Natillas']],
            ['name' => 'Tarta de queso', 'errors' => ['Tarta de queso', 'Tarta de quesoo', 'Tarta de ques']],
            ['name' => 'Helado de vainilla', 'errors' => ['Helado de vainilla', 'Helado de vainia', 'Helado de vainilla']],
            ['name' => 'Bizcocho', 'errors' => ['Bizcocho', 'Bizcocho', 'Biscocho']],
            ['name' => 'Mousse de chocolate', 'errors' => ['Mousse de chocolate', 'Mousse de chocolat', 'Mousse de choclate']],
            ['name' => 'Pudin', 'errors' => ['Pudin', 'Pudin', 'Pudín']],
            ['name' => 'Tiramisú', 'errors' => ['Tiramisú', 'Tiramisu', 'Tiramisú']],
            ['name' => 'Churros', 'errors' => ['Churros', 'Churrros', 'Churros']],
            ['name' => 'Crema catalana', 'errors' => ['Crema catalana', 'Crema catalána', 'Crema catalanna']],
            ['name' => 'Brownie', 'errors' => ['Brownie', 'Brownie', 'Brounie']],
            ['name' => 'Galletas', 'errors' => ['Galletas', 'Galletas', 'Gallettas']],
            ['name' => 'Miel', 'errors' => ['Miel', 'Miel', 'Miell']],
            ['name' => 'Yogur de frutas', 'errors' => ['Yogur de frutas', 'Yogurt de frutas', 'Yogur de frutass']],
            ['name' => 'Helado de fresa', 'errors' => ['Helado de fresa', 'Helado de fresaa', 'Helado de freza']],
            ['name' => 'Tarta de manzana', 'errors' => ['Tarta de manzana', 'Tarta de manzana', 'Tarta de manzanaa']],
            ['name' => 'Leche entera', 'errors' => ['Leche entera', 'Leche enterra', 'Leche enteraa']],
            ['name' => 'Leche desnatada', 'errors' => ['Leche desnatada', 'Leche desnatada', 'Leche desnatadda']],
            ['name' => 'Yogur natural', 'errors' => ['Yogur natural', 'Yogurt natural', 'Yogur natural']],
            ['name' => 'Queso fresco', 'errors' => ['Queso fresco', 'Queso fresko', 'Queso frescco']],
            ['name' => 'Mantequilla', 'errors' => ['Mantequilla', 'Mantequilla', 'Mantekilla']],
            ['name' => 'Nata para cocinar', 'errors' => ['Nata para cocinar', 'Nata para coconar', 'Nata para cocinas']],
            ['name' => 'Queso rallado', 'errors' => ['Queso rallado', 'Queso rallado', 'Queso rayado']],
            ['name' => 'Queso curado', 'errors' => ['Queso curado', 'Queso curado', 'Queso curadoo']],
            ['name' => 'Requesón', 'errors' => ['Requesón', 'Requeson', 'Requesón']],
            ['name' => 'Leche semidesnatada', 'errors' => ['Leche semidesnatada', 'Leche semidesnatada', 'Leche semidesnatdda']],
            ['name' => 'Leche de soja', 'errors' => ['Leche de soja', 'Leche de soja', 'Leche de soya']],
            ['name' => 'Queso azul', 'errors' => ['Queso azul', 'Queso azul', 'Queso azull']],
            ['name' => 'Queso de cabra', 'errors' => ['Queso de cabra', 'Queso de cabra', 'Queso de cabraa']],
            ['name' => 'Margarina', 'errors' => ['Margarina', 'Margarina', 'Margarinaa']],
            ['name' => 'Leche condensada', 'errors' => ['Leche condensada', 'Leche condensada', 'Leche condesada']],
            ['name' => 'Crema de leche', 'errors' => ['Crema de leche', 'Crema de leche', 'Crema de lehe']],
            ['name' => 'Espaguetis', 'errors' => ['Espaguetis', 'Espaguettis', 'Espaguetis']],
            ['name' => 'Macarrones', 'errors' => ['Macarrones', 'Macarones', 'Macarrones']],
            ['name' => 'Tallarines', 'errors' => ['Tallarines', 'Tallarines', 'Tayllarines']],
            ['name' => 'Fideos', 'errors' => ['Fideos', 'Fideos', 'Fideos']],
            ['name' => 'Lasaña', 'errors' => ['Lasaña', 'Lazaña', 'Lasaña']],
            ['name' => 'Raviolis', 'errors' => ['Raviolis', 'Raviolis', 'Raviolis']],
            ['name' => 'Canelones', 'errors' => ['Canelones', 'Canelones', 'Canelones']],
            ['name' => 'Penne', 'errors' => ['Penne', 'Penne', 'Penne']],
            ['name' => 'Farfalle', 'errors' => ['Farfalle', 'Farfalle', 'Farfalle']],
            ['name' => 'Tortellini', 'errors' => ['Tortellini', 'Tortellini', 'Tortelini']],
            ['name' => 'Rigatoni', 'errors' => ['Rigatoni', 'Rigatoni', 'Rigatoni']],
            ['name' => 'Orecchiette', 'errors' => ['Orecchiette', 'Oreciette', 'Orecchiete']],
            ['name' => 'Fusilli', 'errors' => ['Fusilli', 'Fusilli', 'Fusilli']],
            ['name' => 'Cappelletti', 'errors' => ['Cappelletti', 'Cappelletti', 'Cappellety']],
            ['name' => 'Ziti', 'errors' => ['Ziti', 'Ziti', 'Zyti']],
            ['name' => 'Lasagna', 'errors' => ['Lasagna', 'Lazagna', 'Lasaña']],
            ['name' => 'Spaghetti', 'errors' => ['Spaghetti', 'Espaguetti', 'Spagetti']],
            ['name' => 'Tagliatelle', 'errors' => ['Tagliatelle', 'Tagliatelle', 'Tagliatele']],
            ['name' => 'Conchas', 'errors' => ['Conchas', 'Conchas', 'Conchas']],
            ['name' => 'Gnocchi', 'errors' => ['Gnocchi', 'Gnocchi', 'Gnochhi']],
            ['name' => 'Sal', 'errors' => ['Sal', 'Sal', 'Sall']],
            ['name' => 'Azúcar', 'errors' => ['Azucar', 'Azucar', 'Azúcar']],
            ['name' => 'Pimienta negra', 'errors' => ['Pimienta negra', 'Pimienta nega', 'Pimienta negra']],
            ['name' => 'Aceite de oliva', 'errors' => ['Aceite de oliva', 'Aceite de oliba', 'Aceite de olivia']],
            ['name' => 'Vinagre', 'errors' => ['Vinagre', 'Vinagre', 'Vinagre']],
            ['name' => 'Mostaza', 'errors' => ['Mostaza', 'Mostaza', 'Mostasa']],
            ['name' => 'Ketchup', 'errors' => ['Ketchup', 'Kechup', 'Kechap']],
            ['name' => 'Mayonesa', 'errors' => ['Mayonesa', 'Mayonesa', 'Mayonesaa']],
            ['name' => 'Salsa barbacoa', 'errors' => ['Salsa barbacoa', 'Salsa barbakoa', 'Salsa barbacoa']],
            ['name' => 'Salsa de soja', 'errors' => ['Salsa de soja', 'Salsa de soya', 'Salsa de soia']],
            ['name' => 'Orégano', 'errors' => ['Oregano', 'Orégano', 'Oregano']],
            ['name' => 'Comino', 'errors' => ['Comino', 'Comino', 'Comino']],
            ['name' => 'Curry', 'errors' => ['Curry', 'Curry', 'Curi']],
            ['name' => 'Canela', 'errors' => ['Canela', 'Canela', 'Canela']],
            ['name' => 'Clavo', 'errors' => ['Clavo', 'Clavo', 'Clabo']],
            ['name' => 'Nuez moscada', 'errors' => ['Nuez moscada', 'Nuez moskada', 'Nuez moscada']],
            ['name' => 'Pimentón', 'errors' => ['Pimenton', 'Pimentón', 'Pimenton']],
            ['name' => 'Salsa picante', 'errors' => ['Salsa picante', 'Salsa picanti', 'Salsa picante']],
            ['name' => 'Jengibre', 'errors' => ['Jengibre', 'Jengibre', 'Jengibre']],
            ['name' => 'Ajo en polvo', 'errors' => ['Ajo en polvo', 'Ajo en polvo', 'Ajo en polbo']],
            ['name' => 'Salsa tártara', 'errors' => ['Salsa tartara', 'Salsa tártara', 'Salsa tartara']],
            ['name' => 'Perejil', 'errors' => ['Perejil', 'Perejil', 'Perejill']],
            ['name' => 'Albahaca', 'errors' => ['Albahaca', 'Albahaca', 'Albahaza']],
            ['name' => 'Sal de ajo', 'errors' => ['Sal de ajo', 'Sal de ajoy', 'Sal de ajo']],
            ['name' => 'Azúcar moreno', 'errors' => ['Azúcar moreno', 'Azucar moreno', 'Azúcar moreno']],
            ['name' => 'Salsa de tomate', 'errors' => ['Salsa de tomate', 'Salsa de tomete', 'Salsa de tomata']],
            ['name' => 'Salsa de curry', 'errors' => ['Salsa de curry', 'Salsa de curri', 'Salsa de curry']],
            ['name' => 'Salsa de chile', 'errors' => ['Salsa de chile', 'Salsa de chille', 'Salsa de chile']],
            ['name' => 'Salsa César', 'errors' => ['Salsa Cesar', 'Salsa César', 'Salsa Cesar']],
            ['name' => 'Mayonesa ligera', 'errors' => ['Mayonesa ligera', 'Mayonesa ligara', 'Mayonesa ligera']],
            ['name' => 'Mostaza Dijon', 'errors' => ['Mostaza Dijon', 'Mostaza Diyon', 'Mostaza Dijon']],
            ['name' => 'Salsa holandesa', 'errors' => ['Salsa holandesa', 'Salsa holandesa', 'Salsa holandesaa']],
            ['name' => 'Salsa bechamel', 'errors' => ['Salsa bechamel', 'Salsa bechamel', 'Salsa bexamel']],
            ['name' => 'Salsa de yogur', 'errors' => ['Salsa de yogur', 'Salsa de yogurt', 'Salsa de yogur']],
            ['name' => 'Salsa pesto', 'errors' => ['Salsa pesto', 'Salsa pesto', 'Salsa pesto']],
            ['name' => 'Salsa tártara', 'errors' => ['Salsa tartara', 'Salsa tártara', 'Salsa tartara']],
            ['name' => 'Salsa de ajo', 'errors' => ['Salsa de ajo', 'Salsa de ayjo', 'Salsa de ajo']],
            ['name' => 'Salsa de mostaza', 'errors' => ['Salsa de mostaza', 'Salsa de mostaza', 'Salsa de mostaza']],
            ['name' => 'Sal marina', 'errors' => ['Sal marina', 'Sal marina', 'Sal marinna']],
            ['name' => 'Azúcar glas', 'errors' => ['Azucar glas', 'Azúcar glas', 'Azucar glas']],
            ['name' => 'Pimienta blanca', 'errors' => ['Pimienta blanca', 'Pimienta blanca', 'Pimienta blanca']],
            ['name' => 'Pimienta roja', 'errors' => ['Pimienta roja', 'Pimienta roja', 'Pimienta roja']],
            ['name' => 'Salsa de soja baja en sal', 'errors' => ['Salsa de soja baja en sal', 'Salsa de soya baja en sal', 'Salsa de soja baja en sal']],
            ['name' => 'Salsa de chile dulce', 'errors' => ['Salsa de chile dulce', 'Salsa de chille dulce', 'Salsa de chile dulce']],
            ['name' => 'Salsa teriyaki', 'errors' => ['Salsa teriyaki', 'Salsa teriyaki', 'Salsa teriyaki']],
            ['name' => 'Salsa gravy', 'errors' => ['Salsa gravy', 'Salsa gravy', 'Salsa gravi']],
            ['name' => 'Salsa de queso', 'errors' => ['Salsa de queso', 'Salsa de queso', 'Salsa de keso']],
            ['name' => 'Salsa ranchera', 'errors' => ['Salsa ranchera', 'Salsa ranchera', 'Salsa ranchera']],
            ['name' => 'Salsa de menta', 'errors' => ['Salsa de menta', 'Salsa de menta', 'Salsa de menta']],
            ['name' => 'Salsa tártara', 'errors' => ['Salsa tartara', 'Salsa tártara', 'Salsa tartara']],
            ['name' => 'Salsa chimichurri', 'errors' => ['Salsa chimichurri', 'Salsa chimichurri', 'Salsa chimichurry']],
            ['name' => 'Salsa de yogur y pepino', 'errors' => ['Salsa de yogur y pepino', 'Salsa de yogurt y pepino', 'Salsa de yogur y pepino']],
            ['name' => 'Café', 'errors' => ['Cafe', 'Cafee']],
            ['name' => 'Café espresso', 'errors' => ['Cafe espresso', 'Café expresso', 'Cafee espresso']],
            ['name' => 'Café americano', 'errors' => ['Cafe americano', 'Café americno', 'Cafee americano']],
            ['name' => 'Café con leche', 'errors' => ['Cafe con leche', 'Café con leche', 'Cafee con leche']],
            ['name' => 'Café descafeinado', 'errors' => ['Cafe descafeinado', 'Café descafeinado', 'Cafee descafeinado']],
            ['name' => 'Café instantáneo', 'errors' => ['Cafe instantaneo', 'Café instantáneo', 'Cafee instantaneo']],
            ['name' => 'Café molido', 'errors' => ['Cafe molido', 'Café molido', 'Cafee molido']],
            ['name' => 'Café en grano', 'errors' => ['Cafe en grano', 'Café en grano', 'Cafee en grano']],
            ['name' => 'Té negro', 'errors' => ['Te negro', 'Té negro', 'Tee negro']],
            ['name' => 'Té verde', 'errors' => ['Te verde', 'Té verde', 'Tee verde']],
            ['name' => 'Té blanco', 'errors' => ['Te blanco', 'Té blanco', 'Tee blanco']],
            ['name' => 'Té rojo', 'errors' => ['Te rojo', 'Té rojo', 'Tee rojo']],
            ['name' => 'Té chai', 'errors' => ['Te chai', 'Té chai', 'Tee chai']],
            ['name' => 'Té matcha', 'errors' => ['Te matcha', 'Té matcha', 'Tee matcha']],
            ['name' => 'Té Earl Grey', 'errors' => ['Te Earl Grey', 'Té Earl Grey', 'Tee Earl Grey']],
            ['name' => 'Infusión de manzanilla', 'errors' => ['Infusión de manzanilla', 'Infusion de manzanilla', 'Infusión de manzanilla']],
            ['name' => 'Infusión de menta', 'errors' => ['Infusión de menta', 'Infusion de menta', 'Infusión de menta']],
            ['name' => 'Infusión de hierbabuena', 'errors' => ['Infusión de hierbabuena', 'Infusion de hierbabuena', 'Infusión de hierbabuena']],
            ['name' => 'Infusión de tila', 'errors' => ['Infusión de tila', 'Infusion de tila', 'Infusión de tila']],
            ['name' => 'Infusión de valeriana', 'errors' => ['Infusión de valeriana', 'Infusion de valeriana', 'Infusión de valeriana']],
            ['name' => 'Infusión de rooibos', 'errors' => ['Infusión de rooibos', 'Infusion de rooibos', 'Infusión de rooibos']],
            ['name' => 'Café irlandés', 'errors' => ['Cafe irlandés', 'Café irlandes', 'Cafee irlandes']],
            ['name' => 'Café latte', 'errors' => ['Cafe latte', 'Café latte', 'Cafee latte']],
            ['name' => 'Café capuchino', 'errors' => ['Cafe capuchino', 'Café capuchino', 'Cafee capuchino']],
            ['name' => 'Café moka', 'errors' => ['Cafe moka', 'Café moka', 'Cafee moka']],
            ['name' => 'Té con limón', 'errors' => ['Te con limon', 'Té con limón', 'Tee con limon']],
            ['name' => 'Té con leche', 'errors' => ['Te con leche', 'Té con leche', 'Tee con leche']],
            ['name' => 'Té helado', 'errors' => ['Te helado', 'Té helado', 'Tee helado']],
            ['name' => 'Té de jazmín', 'errors' => ['Te de jazmin', 'Té de jazmín', 'Tee de jazmin']],
            ['name' => 'Infusión de hibisco', 'errors' => ['Infusión de hibisco', 'Infusion de hibisco', 'Infusión de hibisco']],
            ['name' => 'Infusión detox', 'errors' => ['Infusión detox', 'Infusion detox', 'Infusión detox']],
            ['name' => 'Infusión relajante', 'errors' => ['Infusión relajante', 'Infusion relajante', 'Infusión relajante']],
            ['name' => 'Infusión digestiva', 'errors' => ['Infusión digestiva', 'Infusion digestiva', 'Infusión digestiva']],
            ['name' => 'Café soluble', 'errors' => ['Cafe soluble', 'Café soluble', 'Cafee soluble']],
            ['name' => 'Café turco', 'errors' => ['Cafe turco', 'Café turco', 'Cafee turco']],
            ['name' => 'Café fuerte', 'errors' => ['Cafe fuerte', 'Café fuerte', 'Cafee fuerte']],
            ['name' => 'Té chai latte', 'errors' => ['Te chai latte', 'Té chai latte', 'Tee chai latte']],
            ['name' => 'Té de menta poleo', 'errors' => ['Te de menta poleo', 'Té de menta poleo', 'Tee de menta poleo']],
            ['name' => 'Infusión de anís', 'errors' => ['Infusión de anís', 'Infusion de anís', 'Infusión de anis']],
            ['name' => 'Infusión de limón', 'errors' => ['Infusión de limón', 'Infusion de limón', 'Infusión de limon']],
            ['name' => 'Café descafeinado instantáneo', 'errors' => ['Cafe descafeinado instantaneo', 'Café descafeinado instantáneo', 'Cafee descafeinado instantaneo']],
            ['name' => 'Café molido espresso', 'errors' => ['Cafe molido espresso', 'Café molido espresso', 'Cafee molido espresso']],
            ['name' => 'Café en cápsulas', 'errors' => ['Cafe en capsulas', 'Café en cápsulas', 'Cafee en capsulas']],
            ['name' => 'Té matcha orgánico', 'errors' => ['Te matcha organico', 'Té matcha orgánico', 'Tee matcha organico']],
            ['name' => 'Infusión de frutos rojos', 'errors' => ['Infusión de frutos rojos', 'Infusion de frutos rojos', 'Infusión de frutos rojos']],
            ['name' => 'Infusión de jengibre', 'errors' => ['Infusión de jengibre', 'Infusion de jengibre', 'Infusión de jengibre']],
            ['name' => 'Té de rosas', 'errors' => ['Te de rosas', 'Té de rosas', 'Tee de rosas']],
            ['name' => 'Té de earl grey descafeinado', 'errors' => ['Te de earl grey descafeinado', 'Té de earl grey descafeinado', 'Tee de earl grey descafeinado']],
            ['name' => 'Infusión de canela', 'errors' => ['Infusión de canela', 'Infusion de canela', 'Infusión de canela']],
            ['name' => 'Infusión detox de limón', 'errors' => ['Infusión detox de limón', 'Infusion detox de limon', 'Infusión detox de limón']],
            ['name' => 'Café de Colombia', 'errors' => ['Cafe de Colombia', 'Café de Colombia', 'Cafee de Colombia']],
            ['name' => 'Pan blanco', 'errors' => ['Pan blando', 'Pan blaco', 'Pan balnco']],
            ['name' => 'Pan integral', 'errors' => ['Pan integal', 'Pan integrall', 'Pan integran']],
            ['name' => 'Pan de centeno', 'errors' => ['Pan de sereno', 'Pan de centano', 'Pan de ceteno']],
            ['name' => 'Pan de molde', 'errors' => ['Pan de mlde', 'Pan de moldeo', 'Pan de molde']],
            ['name' => 'Pan de ajo', 'errors' => ['Pan de ayjo', 'Pan de ajo', 'Pan de ajjo']],
            ['name' => 'Pan de masa madre', 'errors' => ['Pan de masa madre', 'Pan de masa madre', 'Pan de masa madrea']],
            ['name' => 'Baguette', 'errors' => ['Bagette', 'Baguete', 'Bagguette']],
            ['name' => 'Pan de pita', 'errors' => ['Pan de pitta', 'Pan de pta', 'Pan de pitta']],
            ['name' => 'Pan de hamburguesa', 'errors' => ['Pan de hamburgesa', 'Pan de hamburgesa', 'Pan de hamburges']],
            ['name' => 'Pan de hot dog', 'errors' => ['Pan de hotdog', 'Pan de hot-dog', 'Pan de hot-dogg']],
            ['name' => 'Pan rústico', 'errors' => ['Pan rustico', 'Pan rustíco', 'Pan rustíco']],
            ['name' => 'Pan dulce', 'errors' => ['Pan duce', 'Pan dulcce', 'Pan dluce']],
            ['name' => 'Pan francés', 'errors' => ['Pan frances', 'Pan francés', 'Pan françes']],
            ['name' => 'Croissant', 'errors' => ['Croisant', 'Crossaint', 'Croisánt']],
            ['name' => 'Bollo', 'errors' => ['Bolo', 'Bollo', 'Bollo']],
            ['name' => 'Pan de centeno integral', 'errors' => ['Pan de sereno integral', 'Pan de centano integral', 'Pan de ceteno integral']],
            ['name' => 'Pan de avena', 'errors' => ['Pan de abena', 'Pan de avena', 'Pan de avena']],
            ['name' => 'Pan de maíz', 'errors' => ['Pan de maiz', 'Pan de maís', 'Pan de maiz']],
            ['name' => 'Pan de espelta', 'errors' => ['Pan de espelra', 'Pan de espelta', 'Pan de espelta']],
            ['name' => 'Pan de centeno y semillas', 'errors' => ['Pan de sereno y semillas', 'Pan de centano y semillas', 'Pan de ceteno y semillas']],
            ['name' => 'Masa para pizza', 'errors' => ['Maza para pizza', 'Masa para piza', 'Maza para piza']],
            ['name' => 'Masa quebrada', 'errors' => ['Masa qubrada', 'Maza quebrada', 'Masa quebrada']],
            ['name' => 'Masa de hojaldre', 'errors' => ['Maza de hojaldre', 'Masa de hojaldre', 'Masa de hojaldre']],
            ['name' => 'Masa para empanada', 'errors' => ['Maza para empanada', 'Masa para empanda', 'Masa para empanad']],
            ['name' => 'Pan de molde integral', 'errors' => ['Pan de molde integrall', 'Pan de molde integral', 'Pan de molde integran']],
            ['name' => 'Pan de centeno oscuro', 'errors' => ['Pan de sereno oscuro', 'Pan de centano oscuro', 'Pan de ceteno oscuro']],
            ['name' => 'Pan dulce con pasas', 'errors' => ['Pan duce con pasas', 'Pan dulce con pasa', 'Pan dluce con pasas']],
            ['name' => 'Pan sin gluten', 'errors' => ['Pan sin glutten', 'Pan sin glten', 'Pan sin glueten']],
            ['name' => 'Pan de hamburguesa integral', 'errors' => ['Pan de hamburgesa integral', 'Pan de hamburguesa integrall', 'Pan de hamburguesa integran']],
            ['name' => 'Rosquilla', 'errors' => ['Rosquiya', 'Rosqulla', 'Rosquilla']],
            ['name' => 'Magdalena', 'errors' => ['Magdalenaa', 'Magdalena', 'Magdalenaa']],
            ['name' => 'Bizcocho', 'errors' => ['Bizcocho', 'Bizcochoo', 'Biscocho']],
            ['name' => 'Tarta de manzana', 'errors' => ['Tarta de manzana', 'Tarta de manzana', 'Tarta de manzana']],
            ['name' => 'Tarta de chocolate', 'errors' => ['Tarta de chocolatte', 'Tarta de chocolte', 'Tarta de choclate']],
            ['name' => 'Tarta de queso', 'errors' => ['Tarta de queso', 'Tarta de queso', 'Tarta de queso']],
            ['name' => 'Pan de brioche', 'errors' => ['Pan de brioch', 'Pan de brioche', 'Pan de brioch']],
            ['name' => 'Pan de hamburguesa', 'errors' => ['Pan de hamburgesa', 'Pan de hamburguesa', 'Pan de hamburges']],
            ['name' => 'Pan de pita integral', 'errors' => ['Pan de pitta integral', 'Pan de pita integrall', 'Pan de pita integran']],
            ['name' => 'Pan árabe', 'errors' => ['Pan arabe', 'Pan árabe', 'Pan arabe']],
            ['name' => 'Pan de semillas', 'errors' => ['Pan de semilas', 'Pan de semilas', 'Pan de semillas']],
            ['name' => 'Pan dulce relleno', 'errors' => ['Pan duce relleno', 'Pan dulce relleno', 'Pan dluce relleno']],
            ['name' => 'Pan de molde sin corteza', 'errors' => ['Pan de molde sin corteza', 'Pan de molde sin cortez', 'Pan de molde sin corteza']],
            ['name' => 'Pan de centeno con semillas', 'errors' => ['Pan de sereno con semillas', 'Pan de centano con semillas', 'Pan de ceteno con semillas']],
            ['name' => 'Pan de maíz dulce', 'errors' => ['Pan de maiz dulce', 'Pan de maís dulce', 'Pan de maiz dulce']],
            ['name' => 'Pan de focaccia', 'errors' => ['Pan de fokaccia', 'Pan de focaccia', 'Pan de focaccia']],
            ['name' => 'Pan de chapata', 'errors' => ['Pan de chabata', 'Pan de chapata', 'Pan de chapatta']],
            ['name' => 'Pan de molde blanco', 'errors' => ['Pan de molde blando', 'Pan de molde blanco', 'Pan de molde balnco']],
            ['name' => 'Pasta fresca', 'errors' => ['Pasta freca', 'Pasta fresca', 'Pasta fresca']],
            ['name' => 'Pasta seca', 'errors' => ['Pasta seca', 'Pasta seca', 'Pasta seca']],
        ];

        foreach ($items as $data) {
            // Canonical correcto
            $canonical = new Item();
            $canonical->setName($data['name']);
            $canonical->setSlug(new Slug($data['name']));
            $canonical->setCanonical($canonical);
            $manager->persist($canonical);

            // Faltas ortográficas → canonical apunta al correcto
            foreach ($data['errors'] as $errorVariant) {
                $variant = new Item();
                $variant->setName($errorVariant);
                $variant->setSlug(new Slug($errorVariant));
                $variant->setCanonical($canonical);
                $manager->persist($variant);
            }
        }

        $manager->flush();
    }

}